name: Listen on Port 8080
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  listen_on_port_8080:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Netcat
        run: sudo apt-get update && sudo apt-get install -y netcat

      - name: Listen on port 8080
        run: nc -l -p 8080 | while read line; do echo $line; done
