name: Fetch IP Info
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  fetch_ip_info:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      
      - name: Fetch IP info
        run: |
          IP_INFO=$(curl -s https://2ip.ua/ru/api/ip.json)
          echo "IP Info: $IP_INFO"
